### ISSUE TITLE
В архив SortString 3.0.26.0 на Plug-Ring случайно попали changelog и readme.txt от v3.0.25.0

### ISSUE THREAD

**Issue by VictorVG** [andrew-grechkin/cpp#1]
В архив SortString 3.0.26.0 на Plug-Ring случайно попали changelog и readme.txt от v3.0.25.0. Себе взял из архива мастера, и сразу поменял, увидел по диффу ревизии и понял что просто произошла случайная ошибка робота. Наверное у него в тот момент в выходном каталоге сборки оказались старые файлы....

**Comment by andrew-grechkin** [comment]
Да, я тож заметил. Не хотелось выкладывать еще одну версию за сегодня это 4-ый файл
Перевыложил 3.0.26.1

**Comment by VictorVG** [comment]
Я так и понял, житейское. Сам не раз опечатки у себя ловил. Видишь, правишь, но писать в в лог - больше букоф.:) Правлю дату и ладно.:)
