### ISSUE TITLE
Поправил русский LNG под версию 2.3.15 - там строки частично поехали

### ISSUE THREAD

**Issue by VictorVG** [andrew-grechkin/cpp#3]
Сравнил с английским вариантом и поправил русский, ну и доперевёл новые строки. Вроде ничего не сломал, а потому прикладываю - [**svcmgr-ru.lng_2.3.15-fix.zip**](https://github.com/andrew-grechkin/cpp/files/949908/svcmgr-ru.lng_2.3.15-fix.zip).

**Comment by andrew-grechkin** [comment]
Спасибо, я русский никогда не включаю, даже не заметил.
Выложу сегодня обновленную версию

**Comment by VictorVG** [comment]
Я при проверке увидел расхождения. Мелочи.
